CREATE EXTENSION pg_stat_statements;

CREATE USER user_1 WITH ENCRYPTED PASSWORD '';
GRANT ALL PRIVILEGES ON DATABASE zlab TO user_1;

CREATE USER user_2 WITH ENCRYPTED PASSWORD '';
GRANT ALL PRIVILEGES ON DATABASE zlab TO user_2;

CREATE TABLE public.table_1(id SERIAL PRIMARY KEY, value TEXT);
GRANT ALL PRIVILEGES ON TABLE public.table_1 TO user_1;
GRANT ALL PRIVILEGES ON SEQUENCE public.table_1_id_seq TO user_1;


CREATE TABLE public.table_2(id SERIAL PRIMARY KEY, value TEXT);
GRANT ALL PRIVILEGES ON TABLE public.table_2 TO user_2;
GRANT ALL PRIVILEGES ON SEQUENCE public.table_2_id_seq TO user_2;

