version: "3"

services:
  database:
    image: postgres:11
    ports:
      - "8432:5432"
    environment:
      POSTGRES_USER: "db_admin"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "zlab"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./bootstrap/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - ./bootstrap/startup.sh:/docker-entrypoint-initdb.d/startup.sh
      - ./bootstrap/postgresql.conf:/conf/postgresql.conf
      - ./insert_1.sql:/sql/insert_1.sql
      - ./insert_2.sql:/sql/insert_2.sql
